{% set version = "20170220" %}
{% set name = "sagemath-db-polytopes" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://files.sagemath.org/spkg/upstream/polytopes_db/polytopes_db-{{ version }}.tar.bz2
  sha256: cb788bdfca6e00864ec0bfa67932a68ae68bfeb9c527a91be90ad218026a0ce0

build:
  number: 1
  noarch: generic

test:
  commands:
    - test -f $PREFIX/share/reflexive_polytopes/reflexive_polytopes_2d

about:
  home: https://github.com/sagemath/sage
  license: GPLv2+
  summary: This package includes lists of 2- and 3-dimensional reflexive polytopes.

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
