travis:
  secure:
    BINSTAR_TOKEN: AQASzwaBtUhMvDfoFjzOCYjGSJN0ANGUGIhU2lBXE41J63C4iX+4rD5hv6tAf6twOvOFv/muab4kOv5qzO2KkOsYgqF+KtVaocGTntIcjX+RsIc/m5meauvFDad2p/ZNlOEXqMYlThq8IRkQ6wrerHwDn7VEzUbF1ZPI/sYtMwGZhbNX5VELlBOdV57tFxndpNXda42BYSFousRGUg5bI9mBVNwBq9ri0tmrMZBnnyoSpw0xyU7Vu9/ZXZ7pL2noeN/UV9HGqBk3gttM/s5byuy25RngZZuVdHibOsIAlBRrSuRJl5Yb24qm7NN/3veZ+ZK4oP7vjviykE2uU1R76S4714d1W5UXwyl3yDZLOyxizt2FHoSgjSkd9RTNu191DMbSDpjf5wkZ60gV2hBkLt33hb3eDT0aLvjCZZ5gnvEWOkPKxcorJDM5zsQZgwZj/txDffnPfj5ajCRUy9zQLbknW91tg+lEBTu1a0GUaPsXv7BmIeNCIUFtVjic7xbr3pbCNfaPgvJ1tw8oSOI5lD2HZ0ZJeGNSKV5Bfl0LRqdxZuQ9MxMySNeTOYJbVrdrghk4QoTyXEyxdiMus0KAYoErc+cy+cB6vNxfuYBki3uICB2fxIMSea0yy9cLUsH2qCG0JCFbrdGonG6EUMTSk8TlUJVBZ4bBoyGqmKa3Fsk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
